apiVersion: batch/v1
kind: Job
metadata:
  name: category-crawler
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: category-crawler
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "category_crawler.py"]
        env:
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_PASSWORD
          value: mypass
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        image: registry.gitlab.com/fevemania/shopee_side_project/category_crawler:v0.0.2
        name: category-crawler
      initContainers:
      - name: init-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup postgres; do echo waiting for postgres; sleep 2; done;']
      restartPolicy: Never
  backoffLimit: 1
