apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/rabbitmq"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  storageClassName: rabbitmq-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
