apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: mypass
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
      hostname: rabbitmq
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
