apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    app: redis
spec:
  storageClassName: redis-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
