apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopee-restful-api-service
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shopee-restful-api-service-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shopee_restful_api_service"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopee-restful-api-service
  labels:
    app: shopee-restful-api-service
spec:
  storageClassName: shopee-restful-api-service-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
